src/Components/Features/Features.jsx
src/Components/Package/Package.jsx
src/Components/Review/Review.jsx

adds some error fixed

---

src/Components/ChooseUs/ChooseUs.jsx

AOS animation added in why choose us section

Why Choose Us section animation added

---

package-lock.json
package.json

google login authentication issue solved properly

google login authentication issue solved properly

---

src/Components/Navbar/Navbar.jsx
src/Security/ForgetPassword.jsx
src/Security/Login.jsx
src/Security/Register.jsx

login registration and navbar redesign finished properly

login registration and navbar redesign finished properly

---

src/Components/ChooseUs/ChooseUs.jsx

why choose us section design finished with icon properly

why choose us section design finished with icon properly

---

src/Components/Package/Package.jsx

Package section height modified

Package section height modified

---

src/Components/Footer/Footer.jsx
src/Components/MeetTeam/MeetTeam.jsx
src/main.jsx

Meet the team section added

---

src/Components/Checkout/Checkout.jsx
src/Components/Package/Package.jsx
src/Components/PaymentFail/PaymentFail.jsx
src/Components/PaymentSuccess/PaymentSuccess.css
src/Components/PaymentSuccess/PaymentSuccess.jsx

payment fail and payment success page design finished

payment fail and payment success page design finished

---

src/Components/PaymentFail/PaymentFail.css
src/Components/PaymentFail/PaymentFail.jsx
src/Components/PaymentSuccess/PaymentSuccess.jsx

payment fail and success page all issue solve properly

payment fail and success page all issue solve properly

---

src/AdminPannel/AdminHome/AdminHome.jsx

work on admin home

---

package-lock.json
package.json
src/Components/Blog/Blog.jsx
src/Components/Package/Package.jsx
src/Pages/Translate/TranslateFrom.jsx

adds image text to translation

adds image text to translation

---

src/Pages/Translate/TranslateFrom.jsx

some issue solve

---

src/AdminPannel/AdminPages/AddBlogs.jsx

add blog issue resolve

---

src/Components/Navbar/Navbar.jsx
src/Pages/Profile/Profile.jsx
src/main.jsx

profile page done

---

src/Components/Package/Package.jsx
src/Components/PaymentSuccess/PaymentSuccess.jsx

after payment success redirects to translate page properly

after payment success redirects to translate page properly

---

src/Components/AboutUs/AboutUs.jsx
src/Components/Footer/Footer.jsx
src/Components/MeetTeam/MeetTeam.jsx

footer and meet our team anchor tag issue solve properly

footer and meet our team anchor tag issue solve properly

---

package-lock.json
package.json
src/Components/Chat/Chat.jsx
src/Components/Navbar/Navbar.jsx
src/main.jsx

live chat added and also shown in the ui properly

live chat added and also shown in the ui properly

---

package-lock.json
package.json
src/Components/Chat/Chat.jsx

chatbox implemented properly in the user interface

chatbox implemented properly in the user interface

---

src/Components/Chat/Chat.jsx
src/main.jsx

chat page design finished properly

chat page design finished properly

---

package-lock.json
package.json
src/Components/Chat/Chat.jsx
src/Components/Chat/ChatTest.css
src/Components/Chat/ChatTest.jsx
src/Components/Chat/ChatTwo.jsx
src/Components/Chat/chat.css
src/main.jsx

chat page user interface design finished properly

chat page user interface design finished properly

---

src/AxiosFetch/UseBlogs.jsx
src/Components/Blog/Blog.jsx

blog page data fetching issue solve properly

blog page data fetching issue solve properly

---

src/Components/Feedback/Feedback.jsx

feedback page issue solve properly

feedback page issue solve properly

---

src/Components/Chat/ChatTest.jsx

button style change in live support

button style change in live support

---

src/AdminPannel/AdminHome/AdminHome.jsx
src/AdminPannel/AdminPages/UserFeedback/UserFeedback.jsx
src/Pages/LiveChat/LiveChat.jsx
src/Security/LoginFinal.jsx

Dibyendu fix some bugs

---

src/Pages/LiveChat/LiveChat.jsx

working Quick chat support

---

src/Pages/Translate/TranslateFrom.jsx

some modification in translation suggestions

---

package-lock.json
src/Pages/LiveChat/LiveChat.jsx

fix some issue

---

src/Pages/LiveChat/LiveChat.jsx
src/Pages/Profile/Profile.jsx

small change in profile section

small change in profile section

---

src/Components/ChooseUs/ChooseUs.jsx

choose us section card problem solve properly

choose us section card problem solve properly

---

src/Components/PaymentSuccess/PaymentSuccess.jsx

payment page redirect issue solved properly for local host

payment page redirect issue solved properly for local host

---

src/Components/PaymentFail/PaymentFail.jsx
src/Components/PaymentSuccess/PaymentSuccess.jsx

payment success and payment fail page margin issue solve

payment success and payment fail page margin issue solve

---

src/Axios/UseAxiosPublic.jsx
src/Components/Checkout/Checkout.jsx
src/Components/hook/useAdmin.jsx
src/Pages/Translate/TranslateFrom.jsx
src/Security/AdminRoute.jsx
src/main.jsx

Banjirsultana

---

src/Security/Register.jsx

register page design issue solve properly

register page design issue solve properly

---

src/Components/GetInTouch/GetInTouch.jsx

get in touch page margin top issue solve

get in touch page margin top issue solve

---

src/Components/AboutUs/AboutUs.jsx
src/Components/Footer/CookiesPolicy.jsx

cookies policy page text issue solve properly

cookies policy page text issue solve properly

---

src/Components/Footer/PrivacyPolicy.jsx

privacy policy page text issue solve properly

privacy policy page text issue solve properly

---

src/Components/Footer/TermsAndConditionsPage.jsx

terms and conditions page text color issue solve properly

terms and conditions page text color issue solve properly

---

src/Components/AboutUs/AboutUs.jsx

about us page margin top issue solve properly

about us page margin top issue solve properly
